name = "Aeronautics Ups&Downs"
author = "purrson % collie"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e087bec3d3d35ee266449d7ddd67e841662b47051e59f533a8fcb1e8601453b6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
