name = "Aeronautics Ups&Downs"
author = "purrson"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d65334a38211cd262c3fc24efe6515eb8f470dceba19ccc6a9bf91615f76166f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
